### ISSUE TITLE
트랜잭션 조회 오류

### ISSUE THREAD

**Issue by mhhyun** [theloopkr/loopchain_tutorial#5]
최초 tx에 대해서는 조회가 정상적으로 되지만, 두번째 등록된 tx조회부터는 다음과 같이 오류메시지가 발생합니다.
`{
    "response": {
        "code": 9100,
        "jsonrpc": "2.0",
        "message": "<_Rendezvous of RPC that terminated with (StatusCode.UNKNOWN, Exception calling application: local variable 'invoke_result' referenced before assignment)>"
    },
    "response_code": "0"
}`

**Comment by jinhoyoo** [comment]
앗, 그렇군요. 바로 확인을 해보겠습니다.

**Comment by jinhoyoo** [comment]
문서에 오류가 있어서 잘못된 것으로 확인되었습니다. 수정했습니다.
